spin_manifest_version = 2

[application]
name = "blobby-blobby-blobby"
version = "0.1.0"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "blobby-blobby-blobby"

[component.blobby-blobby-blobby]
source = "target/wasm32-wasip1/release/blobby_blobby_blobby.wasm"
allowed_outbound_hosts = []
blob_containers = ["default", "azz", "aws"]
[component.blobby-blobby-blobby.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
